# This override file should be used when running this service in isolation to provide dependencies and expose ports for local testing
services:
  node-express-template:
    build:
      target: development
    image: node-express-template-development
    container_name: node-express-template-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./scripts:/home/node/scripts
      - ./package.json:/home/node/package.json